/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.silvanolte.koans

import kotlin.test.Test
import kotlin.test.assertEquals

class IntroductionTest {

    @Test fun testHelloWorld() {
        val classUnderTest = Introduction()
        assertEquals("OK", classUnderTest.start())
    }

    @Test fun testNamedArguments() {
        val classUnderTest = Introduction()
        assertEquals("[a, b]", classUnderTest.joinOptions(listOf("a","b")))
    }

    @Test fun testDefaultArguments() {
        val classUnderTest = Introduction()
        assertEquals(listOf("a42","b1","C42","D2"), classUnderTest.useFoo())
    }

    @Test fun testLambdas() {
        val classUnderTest = Introduction()
        assertEquals(true, classUnderTest.containsEven(listOf(1,2,3)))
        assertEquals(false, classUnderTest.containsEven(listOf(1,3,5)))
    }

}
