/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.silvanolte.koans

class Introduction {

    fun start(): String = "OK"

    fun joinOptions(options: Collection<String>) = options.joinToString(prefix = "[", postfix = "]")
}
