/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.silvanolte.koans

class Introduction {

    fun start(): String = "OK"

    fun joinOptions(options: Collection<String>) = options.joinToString(prefix = "[", postfix = "]")

    fun foo(name: String, number: Int = 42, toUpperCase: Boolean = false) =
        (if (toUpperCase) name.toUpperCase() else name) + number
    
    fun useFoo() = listOf(
        foo("a"),
        foo("b", number = 1),
        foo("c", toUpperCase = true),
        foo(name = "d", number = 2, toUpperCase = true)
    )

    fun containsEven(collection: Collection<Int>): Boolean = collection.any { i: Int -> i % 2 == 0 }

}
